#!/bin/bash

sudo apt-get update

echo 'Install common tools'
echo '-----------------'
sudo apt-get install git curl wget build-essential zsh -y


# Hide "last login" line when starting a new terminal session
touch $HOME/.git-credentials

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.aliases $HOME/.aliases


echo 'Install node'
echo '-----------'
sudo mkdir -p /usr/local/n
sudo chown -R $(whoami) /usr/local/n
# take ownership of node install destination folders
sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
bash n lts
rm -rf n

echo 'Install Yarn'
echo '------------'
npm install -g yarn

# echo 'Install cypress tools'
# sudo apt install libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 -y

#echo 'Install Java'
#echo '------------'
#sudo add-apt-repository ppa:linuxuprising/java -y
#sudo apt update
#sudo apt-get install oracle-java13-installer -y
#sudo apt-get install oracle-java13-set-default -y


echo 'Install zsh-autosuggestions'
echo '---------------------------'
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions


echo 'Install zsh-syntaxthilight'
echo '---------------------------'
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo 'Install zsh-powerlevel10k'
echo '---------------------------'
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k

ln -s $HOME/.dotfiles/shell/.p10k.zsh $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig

chsh -s $(which zsh)

echo 'Starting Dbus'
sudo /etc/init.d/dbus start &> /dev/null


echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
