#!/bin/bash

sudo apt-get update

echo 'Install common tools'
echo '-----------------'
sudo apt-get install git curl wget file build-essential zsh -y


# Hide "last login" line when starting a new terminal session
touch $HOME/.git-credentials

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.aliases $HOME/.aliases


echo 'Install Homebrew'
echo '--------------------'
git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
mkdir ~/.linuxbrew/bin
ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
eval $(~/.linuxbrew/bin/brew shellenv)


echo 'Update brew'
echo '-----------'
brew update

echo 'Install node'
echo '-----------'
brew install node

echo 'Install Yarn'
echo '------------'
npm install -g yarn

# install jre
echo 'Install java 11'
echo '----------------'
brew install openjdk@11

# echo 'Install cypress tools'
# sudo apt install libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 -y

#echo 'Install Java'
#echo '------------'
#sudo add-apt-repository ppa:linuxuprising/java -y
#sudo apt update
#sudo apt-get install oracle-java13-installer -y
#sudo apt-get install oracle-java13-set-default -y


echo 'Install zsh-autosuggestions'
echo '---------------------------'
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions


echo 'Install zsh-syntaxthilight'
echo '---------------------------'
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo 'Install zsh-powerlevel10k'
echo '---------------------------'
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k

echo 'Install Spaceship Prompt'
echo '---------------------------'
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1

ln -s ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/spaceship-prompt/spaceship.zsh-theme ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/spaceship.zsh-theme
ln -s $HOME/.dotfiles/shell/.p10k.zsh $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig

chsh -s $(which zsh)

echo 'Starting Dbus'
sudo /etc/init.d/dbus start &> /dev/null


echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
